import { formatDateTime } from "./formatting";

export function buildTextReport(review) {
  const passed = review.summary?.passed ?? 0;
  const needsReview = review.summary?.needsReview ?? 0;
  const missing = review.summary?.missing ?? 0;
  const totalItems = review.summary?.totalItems ?? 0;

  const resultLines = review.results
    ?.map(
      (result, index) =>
        `${index + 1}. ${result.requirement}
Status: ${result.resultStatus}
Description: ${result.description}
Matched Text: ${result.matchedText || "None"}
Recommendation: ${result.recommendation}
Score: ${result.score} / ${result.weight}`
    )
    .join("\n\n");

  return `POLICYGUARD COMPLIANCE REPORT

Review Title: ${review.title}
Checklist: ${review.checklist}
Overall Score: ${review.overallScore}%
Status: ${review.status}
Review Date: ${formatDateTime(review.createdAt)}

EXECUTIVE SUMMARY
Passed: ${passed}
Needs Review: ${needsReview}
Missing: ${missing}
Total Checklist Items: ${totalItems}

ASSESSMENT SUMMARY
This report summarizes the policy or procedure review completed by PolicyGuard. The review compares the submitted document against the selected compliance checklist and identifies passed requirements, items needing additional review, and missing documentation elements.

DETAILED RESULTS

${resultLines || "No detailed results available."}

SCORING METHOD
Passed items receive full weight. Items marked Needs Review receive partial credit. Missing items receive zero points.

Generated by PolicyGuard Compliance Analyzer.
`;
}