// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolicyGuard.Api.Data;

#nullable disable

namespace PolicyGuard.Api.Migrations
{
    [DbContext(typeof(PolicyGuardDbContext))]
    [Migration("20260518015343_AddAudityLogs")]
    partial class AddAudityLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PolicyGuard.Api.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("PolicyGuard.Api.Models.ChecklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComplianceChecklistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requirement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComplianceChecklistId");

                    b.ToTable("ChecklistItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComplianceChecklistId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The policy should clearly explain its purpose, objective, or intent.",
                            Keywords = "purpose, objective, intent, goal",
                            Requirement = "Purpose Statement",
                            Weight = 10
                        },
                        new
                        {
                            Id = 2,
                            ComplianceChecklistId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The policy should define who and what the policy applies to.",
                            Keywords = "scope, applies to, applicable, coverage",
                            Requirement = "Scope",
                            Weight = 10
                        },
                        new
                        {
                            Id = 3,
                            ComplianceChecklistId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The policy should identify responsible parties and their duties.",
                            Keywords = "roles, responsibilities, accountable, owner, duties",
                            Requirement = "Roles and Responsibilities",
                            Weight = 10
                        },
                        new
                        {
                            Id = 4,
                            ComplianceChecklistId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The policy should address security expectations or safeguards.",
                            Keywords = "security, safeguard, protection, vulnerability, risk",
                            Requirement = "Security Considerations",
                            Weight = 10
                        },
                        new
                        {
                            Id = 5,
                            ComplianceChecklistId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The policy should explain access control, permissions, or authorization requirements.",
                            Keywords = "access control, permission, authorization, authentication, least privilege",
                            Requirement = "Access Control",
                            Weight = 10
                        },
                        new
                        {
                            Id = 6,
                            ComplianceChecklistId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The policy should describe how sensitive, confidential, or operational data is handled.",
                            Keywords = "data handling, confidential, sensitive data, privacy, retention",
                            Requirement = "Data Handling",
                            Weight = 10
                        },
                        new
                        {
                            Id = 7,
                            ComplianceChecklistId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The policy should state when it will be reviewed or updated.",
                            Keywords = "review schedule, annual review, reviewed, updated, maintenance",
                            Requirement = "Review Schedule",
                            Weight = 10
                        },
                        new
                        {
                            Id = 8,
                            ComplianceChecklistId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The policy should identify approval requirements or approving authority.",
                            Keywords = "approval, approved by, signoff, authorized by, approver",
                            Requirement = "Approval Process",
                            Weight = 10
                        },
                        new
                        {
                            Id = 9,
                            ComplianceChecklistId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The policy should explain how compliance will be enforced.",
                            Keywords = "enforcement, violation, noncompliance, disciplinary, corrective action",
                            Requirement = "Enforcement Statement",
                            Weight = 10
                        },
                        new
                        {
                            Id = 10,
                            ComplianceChecklistId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The policy should include revision history or version tracking.",
                            Keywords = "revision history, version, change log, last updated, document history",
                            Requirement = "Revision History",
                            Weight = 10
                        },
                        new
                        {
                            Id = 11,
                            ComplianceChecklistId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The documentation should explain the project purpose and business need.",
                            Keywords = "project purpose, business need, objective, problem statement",
                            Requirement = "Project Purpose",
                            Weight = 10
                        },
                        new
                        {
                            Id = 12,
                            ComplianceChecklistId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The documentation should define business requirements.",
                            Keywords = "business requirement, business requirements, stakeholder need, requirement",
                            Requirement = "Business Requirements",
                            Weight = 10
                        },
                        new
                        {
                            Id = 13,
                            ComplianceChecklistId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The documentation should define functional requirements.",
                            Keywords = "functional requirement, user story, system shall, feature",
                            Requirement = "Functional Requirements",
                            Weight = 10
                        },
                        new
                        {
                            Id = 14,
                            ComplianceChecklistId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The documentation should define technical requirements or constraints.",
                            Keywords = "technical requirement, architecture, system design, database, API",
                            Requirement = "Technical Requirements",
                            Weight = 10
                        },
                        new
                        {
                            Id = 15,
                            ComplianceChecklistId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The documentation should include a testing plan.",
                            Keywords = "testing plan, test case, quality assurance, QA, validation",
                            Requirement = "Testing Plan",
                            Weight = 10
                        },
                        new
                        {
                            Id = 16,
                            ComplianceChecklistId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The documentation should describe User Acceptance Testing.",
                            Keywords = "UAT, user acceptance testing, acceptance criteria, business validation",
                            Requirement = "UAT Process",
                            Weight = 10
                        },
                        new
                        {
                            Id = 17,
                            ComplianceChecklistId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The documentation should include deployment planning.",
                            Keywords = "deployment plan, release plan, implementation plan, go live",
                            Requirement = "Deployment Plan",
                            Weight = 10
                        },
                        new
                        {
                            Id = 18,
                            ComplianceChecklistId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The documentation should describe ongoing support or maintenance.",
                            Keywords = "maintenance plan, support plan, operations, monitoring",
                            Requirement = "Maintenance Plan",
                            Weight = 10
                        },
                        new
                        {
                            Id = 19,
                            ComplianceChecklistId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The documentation should identify risks and mitigation plans.",
                            Keywords = "risk assessment, risk, mitigation, impact, likelihood",
                            Requirement = "Risk Assessment",
                            Weight = 10
                        },
                        new
                        {
                            Id = 20,
                            ComplianceChecklistId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The documentation should include approval or signoff expectations.",
                            Keywords = "approval, signoff, approved by, stakeholder approval",
                            Requirement = "Approval and Signoff",
                            Weight = 10
                        },
                        new
                        {
                            Id = 21,
                            ComplianceChecklistId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The change request should clearly describe the proposed change.",
                            Keywords = "change description, proposed change, request summary, modification",
                            Requirement = "Change Description",
                            Weight = 10
                        },
                        new
                        {
                            Id = 22,
                            ComplianceChecklistId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The change request should explain why the change is needed.",
                            Keywords = "business justification, justification, business need, reason",
                            Requirement = "Business Justification",
                            Weight = 10
                        },
                        new
                        {
                            Id = 23,
                            ComplianceChecklistId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The change request should explain expected impact.",
                            Keywords = "impact analysis, impact, affected users, affected systems",
                            Requirement = "Impact Analysis",
                            Weight = 10
                        },
                        new
                        {
                            Id = 24,
                            ComplianceChecklistId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The change request should define risk level or risk rating.",
                            Keywords = "risk level, risk rating, high risk, medium risk, low risk",
                            Requirement = "Risk Level",
                            Weight = 10
                        },
                        new
                        {
                            Id = 25,
                            ComplianceChecklistId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The change request should include a rollback or backout plan.",
                            Keywords = "rollback plan, backout plan, restore, revert",
                            Requirement = "Rollback Plan",
                            Weight = 10
                        },
                        new
                        {
                            Id = 26,
                            ComplianceChecklistId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The change request should include testing before or after implementation.",
                            Keywords = "testing plan, test, validation, verification",
                            Requirement = "Testing Plan",
                            Weight = 10
                        },
                        new
                        {
                            Id = 27,
                            ComplianceChecklistId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The change request should define when the change will be implemented.",
                            Keywords = "implementation schedule, implementation date, timeline, maintenance window",
                            Requirement = "Implementation Schedule",
                            Weight = 10
                        },
                        new
                        {
                            Id = 28,
                            ComplianceChecklistId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The change request should define approval requirements.",
                            Keywords = "approval, approved by, change advisory board, CAB, signoff",
                            Requirement = "Approval Process",
                            Weight = 10
                        },
                        new
                        {
                            Id = 29,
                            ComplianceChecklistId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The change request should explain who will be notified and how.",
                            Keywords = "communication plan, notify, notification, stakeholders, users",
                            Requirement = "Communication Plan",
                            Weight = 10
                        },
                        new
                        {
                            Id = 30,
                            ComplianceChecklistId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The change request should include a post-change review or validation step.",
                            Keywords = "post-change review, review, lessons learned, validation, follow-up",
                            Requirement = "Post-Change Review",
                            Weight = 10
                        });
                });

            modelBuilder.Entity("PolicyGuard.Api.Models.ComplianceChecklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ComplianceChecklists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Information Technology",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reviews IT policies for required governance, security, access control, and maintenance sections.",
                            Name = "IT Policy Checklist"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Software Development",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reviews software project documentation for SDLC readiness, testing, deployment, and approval coverage.",
                            Name = "SDLC Documentation Checklist"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Change Management",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reviews change management documentation for risk, impact, approval, rollback, and post-change review items.",
                            Name = "Change Management Checklist"
                        });
                });

            modelBuilder.Entity("PolicyGuard.Api.Models.PolicyReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComplianceChecklistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OverallScore")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ComplianceChecklistId");

                    b.ToTable("PolicyReviews");
                });

            modelBuilder.Entity("PolicyGuard.Api.Models.ReviewResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChecklistItemId")
                        .HasColumnType("int");

                    b.Property<string>("MatchedText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PolicyReviewId")
                        .HasColumnType("int");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistItemId");

                    b.HasIndex("PolicyReviewId");

                    b.ToTable("ReviewResults");
                });

            modelBuilder.Entity("PolicyGuard.Api.Models.ChecklistItem", b =>
                {
                    b.HasOne("PolicyGuard.Api.Models.ComplianceChecklist", "ComplianceChecklist")
                        .WithMany("Items")
                        .HasForeignKey("ComplianceChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComplianceChecklist");
                });

            modelBuilder.Entity("PolicyGuard.Api.Models.PolicyReview", b =>
                {
                    b.HasOne("PolicyGuard.Api.Models.ComplianceChecklist", "ComplianceChecklist")
                        .WithMany()
                        .HasForeignKey("ComplianceChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComplianceChecklist");
                });

            modelBuilder.Entity("PolicyGuard.Api.Models.ReviewResult", b =>
                {
                    b.HasOne("PolicyGuard.Api.Models.ChecklistItem", "ChecklistItem")
                        .WithMany()
                        .HasForeignKey("ChecklistItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PolicyGuard.Api.Models.PolicyReview", "PolicyReview")
                        .WithMany("Results")
                        .HasForeignKey("PolicyReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistItem");

                    b.Navigation("PolicyReview");
                });

            modelBuilder.Entity("PolicyGuard.Api.Models.ComplianceChecklist", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PolicyGuard.Api.Models.PolicyReview", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
